version: '3'

services:
  postgres:
    container_name: postgres-dev
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:    
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data

  rabbitmq:
    container_name: rabbitmq-dev
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  auction_svc:
    image: luccalkm/auction_svc:latest
    build:
      context: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

volumes:
  mongodata:
  pgdata:

